version: '3'
services:
  backend:
    container_name: back
    build:
      context: .
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://host.docker.internal:27017/transport
    
  frontend:
    container_name: front
    build:
      context: ./client
    ports:
      - "3000:3000" 
    stdin_open: true
    tty: true
    depends_on:
      - backend
